funds_tracker/urls.py
#! /usr/bin/env python
"""!
-----------------------------------------------------------------------------
File Name : urls.py

Purpose: url handler for funds_tracker app

Created: 01-Mar-2015 23:32:20 AEDT
-----------------------------------------------------------------------------
Revision History



-----------------------------------------------------------------------------
S.D.G
"""
__author__ = 'Ben Johnston'
__revision__ = '0.1'
__date__ = '01-Mar-2015 23:32:20 AEDT'
__license__ = 'MPL v2.0'

# LICENSE DETAILS############################################################
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# IMPORTS#####################################################################
from django.conf import settings
from django.conf.urls import patterns, url
from django.conf.urls.static import static
from funds_tracker import views
##############################################################################

urlpatterns = patterns('',
                       url(r'^$', views.IndexView.as_view(), name='index'),
                       url(r'^logos/$', views.ImageView.as_view(),
                           name='funds-tracker-logos'),
                       url(r'^partyview/(?P<pk>[^/]+)/$', views.PartySummaryView,
                           name='party-view'),
                       url(r'^party/(?P<pk>[^/]+)/year/(?P<pk_y>\w+)/$',
                           views.PartyYearView, name='party-year'),
                       url(r'^donor/(?P<pk>[^/]+)/$', views.DonorView,
                           name='donor-view'),
                       url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
                                                    'document_root': settings.MEDIA_ROOT,
                                                    'show_indexes': True})
                       )
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

partyCoin_interface/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^funds_tracker/', include('funds_tracker.urls', namespace='funds'))
)

funds_tracker/models.py
from django.conf import settings
from django.db import models

# Create your models here.
class Donation(models.Model):
    year = models.CharField(max_length=20, default='')
    party = models.CharField(max_length=200, default='')
    donor = models.CharField(max_length=200, default='')
    address = models.CharField(max_length=200, default='')
    party_state = models.CharField(max_length=4, default='')
    state = models.CharField(max_length=3, default='')
    postcode = models.CharField(max_length=4, default='')
    donor_type = models.CharField(max_length=40, default='')
    amount = models.FloatField(default=0.0)

    def get_year(self):
        return self.year.__str__()

    def get_party(self):
        return self.party.__str__()

    def get_donor(self):
        return self.donor.__str__()

    def get_address(self):
        return self.address.__str__()

    def get_state(self):
        return self.state.__str__()

    def get_postcode(self):
        return self.postcode.__str__()

    def get_donor_type(self):
        return self.donor_type.__str__()

    def __str__(self):
        return '%s-%s:%s:$%0.2f' % (
               self.get_year(),
               self.get_party(),
               self.get_donor(),
               self.amount)


class PartyInfo(models.Model):
    party = models.CharField(max_length=200, default='')
    logo = models.CharField(max_length=500, default='')
    wiki_page = models.CharField(max_length=500, default='')

funds_tracker/views.py
#! /usr/bin/env python
"""!
-----------------------------------------------------------------------------
File Name: views.py

Purpose: funds_tracker app views script

Created: Wed Mar 11 13:07:22 AEDT 2015
-----------------------------------------------------------------------------
Revision History



-----------------------------------------------------------------------------
S.D.G
"""
__author__ = 'Ben Johnston'
__revision__ = '0.1'
__date__ = "Wed Mar 11 13:07:30 AEDT 2015"
__license__ = 'MPL v2.0'

# LICENSE DETAILS############################################################
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://moziljla.org/MPL/2.0/.

# Django usage is subject to the terms and conditions of the FREE-BSD license
# https://github.com/django/django/blob/master/LICENSE
# IMPORTS#####################################################################

from django.shortcuts import render
from django.views import generic
from collections import OrderedDict
from funds_tracker.models import Donation, PartyInfo
from django.db.models import Max, Sum
from settings import STATES_ABBR, STATES_LIST

import operator
from utilities import get_donation_year_total
from django.template.defaulttags import register

##############################################################################
# The number of top parties to list in the summary
NO_TOP_PARTIES = 4
LIBERAL_BLUE = '#1e6f88'
ALP_RED = '#B83537'
PALMER_YELLOW = '#dfff2c'
GREENS_GREEN = '#34e01d'
OTHERS = '#CA6FD6'
COLOURS = []


@register.filter
def get_item(dictionary, key):
    return dictionary.get(key)


@register.filter(name='clean')
def clean_filter(xargs):
    return str(xargs.strip(' '))


@register.filter(name='sort')
def sort_dict(value):
    if isinstance(value, dict):
        new_dict = OrderedDict()
        sorted_items = sorted(value.items())
        for item in sorted_items:
            new_dict[item[1]] = item[0]

        return new_dict
    elif isinstance(value, list):
        return sorted(value)
    else:
        return value


def get_summary(state):
    # Get the most recent year
    max_year = Donation.objects.all().aggregate(Max('year'))['year__max']
    # Get all objects for that year
    max_year_objects = Donation.objects.filter(year=max_year.__str__(),
                                               party_state=state.lower())
    parties = max_year_objects.values_list('party', flat=True).\
        order_by('party').distinct()
    # Get the totals for the most funded parties
    totals = {}
    grand_total = 0
    for party in parties:
        totals[party] = max_year_objects.filter(party=party).\
            aggregate(Sum('amount'))['amount__sum'].__int__()
        grand_total += totals[party]
    sorted_totals = sorted(totals.items(), key=operator.itemgetter(1),
                           reverse=True)
    # Create a blank list to return
    filtered_parties = []
    filtered_names = []
    filtered_values = []
    if len(totals) < NO_TOP_PARTIES:
        no_of_parties = len(totals)
    else:
        no_of_parties = NO_TOP_PARTIES
    # Return only the most well funded parties
    for i in range(no_of_parties):
        filtered_parties.append((sorted_totals[i][0].__str__(),
                                sorted_totals[i][1]))
        filtered_names.append(sorted_totals[i][0].__str__())
        filtered_values.append(sorted_totals[i][1])

    filtered_names.append('Others')
    filtered_values.append(grand_total - sum(filtered_values))
    # Get the logos and wiki pages of the most well funded parties
    for i in range(len(filtered_parties)):
        w_l = PartyInfo.objects.filter(party=filtered_parties[i][0]).\
            values('logo', 'wiki_page')
        # try:
        filtered_parties[i] += (w_l[0]['logo'], w_l[0]['wiki_page'])
        # except:
        # TODO handle this better
        # pass

    return (max_year, filtered_parties, filtered_names, filtered_values)


# Rename to summaryview
class IndexView(generic.ListView):
    # model = Donation
    template_name = 'funds_tracker/index.html'
    context_object_name = 'major_national_parties'

    def get_queryset(self):
        max_year_FED, filtered_parties_FED, filtered_names, filtered_values = \
            get_summary('FED')
        # Colours for pie chart
        COLOURS = []
        # TODO add database of colour codes for parties
        for name in filtered_names:
            if name.lower().find('liberal') >= 0:
                COLOURS.append(LIBERAL_BLUE)
            elif name.lower().find('labor') >= 0:
                COLOURS.append(ALP_RED)
            elif name.lower().find('palmer') >= 0:
                COLOURS.append(PALMER_YELLOW)
            elif name.lower().find('greens') >= 0:
                COLOURS.append(GREENS_GREEN)
            else:
                COLOURS.append(OTHERS)

        # Create a dictionary for statewide summaries
        state_names = []
        state_values = {}

        # Get the state results
        for state in STATES_LIST:
            max_year, filtered_parties, filtered_names, filtered_values = \
                get_summary(state)
            state_names.append(STATES_ABBR[state])
            state_values[STATES_ABBR[state]] = filtered_parties

        # print state_values['New South Wales']

        # Generate chart data
        chart_data = []
        for i in range(len(filtered_parties_FED)):
            chart_data.append((filtered_parties_FED[i][0],
                              (filtered_parties_FED[i][1] / 1000)))

        return {'year': '%s - %d' % (max_year_FED, int(max_year_FED) + 1),
                'summary': filtered_parties_FED,
                'state_names': state_names,
                'state_values': state_values,
                'chart_data': filtered_parties_FED,
                # 'chart': chart,
                }


class ImageView(generic.ListView):
    model = PartyInfo
    template_name = 'funds_tracker/logos.html'
    context_object_name = 'partyInfo'

    def get_queryset(self):
        return PartyInfo.objects.all().order_by('party')


def PartySummaryView(request, pk):
    party = PartyInfo.objects.filter(party=str(pk).strip(' '))
    years = Donation.objects.filter(party=pk).order_by('-year')\
        .values_list('year', flat=True).distinct()
    amounts_by_year = {}
    amounts = []
    for year in years:
        amounts_by_year[str(year)] = round(get_donation_year_total(pk, year), 0)
        amounts.append(amounts_by_year[str(year)])

    context = {
        'name': pk,
        'party': party,
        'years': years,
        'amounts_by_year': amounts_by_year,
        'chart_data': amounts_by_year,
    }

    template_name = 'funds_tracker/partyView.html'

    return render(request, template_name, context)


def PartyYearView(request, pk, pk_y):
    partyInfo = Donation.objects.filter(party=str(pk).strip(' '),
                                        year=str(pk_y).strip(' ')).order_by('-amount')

    template_name = 'funds_tracker/detailView.html'

    names = []
    amounts = []
    amounts_by_name = {}
    amounts_by_value = {}

    for party in partyInfo:
        names.append(party.get_donor())
        amounts.append(party.amount)
        amounts_by_name[party.get_donor()] = party.amount
        amounts_by_value[party.amount] = party.get_donor()

    context = {
        'party': pk,
        'year': pk_y,
        'names': names,
        'amounts': amounts,
        'amounts_by_name': amounts_by_name,
        'amounts_by_value': amounts_by_value,
    }

    return render(request, template_name, context)


def DonorView(request, pk):

    template_name = 'funds_tracker/donorView.html'
    context = {}

    return render(request, template_name, context)

funds_tracker/templates/funds_tracker/detailView.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>partyCoin - Australia's Political Party Funds Tracker </title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
        
        <script type="text/javascript" src="https://www.google.com/jsapi"></script>
        <script type="text/javascript">google.load("visualization", "1", {packages:["corechart"]});
        </script>
    </head>
    {% load humanize %}
    <body>
    <div class="container">
        <h1>Detailed Party View: {{ party }}, {{ year }}</h1>
    </div>
    <div class="container">
        <h2>Annual Donations </h2>
            <div class="col-lge-1">
                <img src="data:image/png;base64,{{ chart }}"/> 
            </div>

            <div class="col-lge-2">
                {% for item in amounts_by_value.items|sort reversed %}
                    <div class="col-sml-2">
                        <p align="center"> <a href="/funds_tracker/donor/"> {{ item.1 }} </a></p>
                        <p align="center"> ${{ item.0|intcomma }} </p>
                    </div>
                {% endfor %}
            </div>
    </div>
    </body>
</html>

funds_tracker/templates/funds_tracker/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
    {% load humanize %}
        <title>partyCoin - Australia's Political Party Funds Tracker </title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
        
        <script type="text/javascript" src="https://www.google.com/jsapi"></script>
        <script type="text/javascript">
          google.load("visualization", "1", {packages:["corechart"]});
          google.setOnLoadCallback(drawChart);
          function drawChart() {

            var data = google.visualization.arrayToDataTable([
                    ['Party', 'Funding', {type: 'string', role: 'tooltip'}],

                {% for value in major_national_parties.chart_data %}
                [ '{{ value.0 }}', {{ value.1 }} , '{{ value.0 }} ${{value.1|intcomma}}'],

                {% endfor %}

            ]);

            var options = {
                'legend': 'left',
                'title': 'Federal Party Funding',
            };

            var piechart_div = document.getElementById('piechart_div');
            var chart = new google.visualization.PieChart(piechart_div);

            /*google.visualization.events.addListener(chart, 'ready', function () {
                    piechart_div.innerHTML = '<img src="' + chart.getImageURI() + '">';
                    console.log(piechart_div.innerHTML);
                    });
                    */

            chart.draw(data, options);
          }
        </script>
    </head>
    <body>
    <h1>Reporting Period: {{major_national_parties.year}}</h1>
    <h2>Federal Parties</h2>
    {% if major_national_parties %}
    <table >
            <tr>
                <td rowspan=13 valign="center">
                    <div id="piechart_div" style="width: 800px; height: 600px;"></div>

                </td>
            </tr>
            {% for value in major_national_parties.summary %}
            <tr>
                <td></td>
                <td style="padding: 15px;" align="center"><img src="{{value.2}}" style="height:100px" class="img-responsive"></td>
            </tr>
            <tr>
                <td></td>
                <td align="center"><a href="{% url 'funds:party-view' pk=value.0|clean %}"> {{ value.0 }} </a></td>
            </tr>
            <tr>
                <td></td>
                <td align="center">${{value.1|intcomma}}</td>
            </tr>
                {% endfor %} 
        </table>
    {% endif %}

    {% for key, value in major_national_parties.state_values.items|sort %}
    <div class="container">
        <h2>{{key}}</h2>
            <div class="row">
            {% for details in value %}
                <div class="col-lg-3">
                    <p align="center"><img src="{{details.2}}" style="height:100px" class="img-responsive"></p>
                    <p align="center">{{details.0}}</p>
                    <p align="center">${{details.1|intcomma}}</p>
                </div>
            {% endfor %}
            </div>
    </div>
    {% endfor %} 
    </body>
</html>

funds_tracker/templates/funds_tracker/logos.html
{% load staticfiles %}
<html>
<h1>Logos</h1>
<table>
{% for party in partyInfo %}
<tr><td><a href="{{party.wiki_page}}"> {{party.party}} </td>
        <td><img src="{{party.logo}}" style="height:50px"
            alt="No logo available"/></a></td>
</tr> 
{% endfor %}
</table>
</html>

funds_tracker/templates/funds_tracker/partyView.html
<!DOCTYPE html>
<html lang="en">
    <head>
    {% load humanize %}
        <title>partyCoin - Australia's Political Party Funds Tracker </title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
        
        <script type="text/javascript" src="https://www.google.com/jsapi"></script>
        <script type="text/javascript">
          google.load("visualization", "1", {packages:["corechart"]});
          google.setOnLoadCallback(drawChart);
          function drawChart() {

            var data = google.visualization.arrayToDataTable([
                    ['Party', 'Funding', {type: 'string', role: 'tooltip'}],

                {% for key, value in chart_data.items %}
                    [ '{{ key }}', {{ value }} , '{{ key }}: ${{value|intcomma}}'],

                {% endfor %}

            ]);

            var options = {
                'legend': 'left',
                'title': 'Federal Party Funding',
            };

            var chart = new
                google.visualization.ColumnChart(document.getElementById('colchart_div'));

            /*google.visualization.events.addListener(chart, 'ready', function () {
                    piechart_div.innerHTML = '<img src="' + chart.getImageURI() + '">';
                    console.log(piechart_div.innerHTML);
                    });
                    */

            chart.draw(data, options);
          }
        </script>
    </head>
    <body>
    <div class="container">
        <h1>Detailed Party View: {{ name }}</h1>
    </div>
    <div class="container">
        <h2>Annual Donations </h2>
        <div id="colchart_div" style="width: 800px; height: 600px;"></div>
            <div class="row">
                {% for key, value in amounts_by_year.items %}
                    <div class="col-lg-2">
                        <p align="center"> <a href="{% url 'funds:party-year' name key %}"> {{key}} </a></p>
                        <p align="center"> ${{value|intcomma}} </p>
                    </div>
                {% endfor %}
            </div>
    </div>
    </body>
</html>